appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: TlguMQuxYb5XUSX/6tIw64esl1B+YC3zo/QR4Vq/hZC8i06if5dAI08Cnvn0tFq5p55Lz5nNwkiocCb8y/fecC+BoKOKv1A09XL13S7DxDE8gHte86Tb1JVJbZWI0xJlW/wjT2VQ5piyy6Lg82E/egiNp2lRQ0nlEsK4FfqDlfN1tFu1BOASaRTXm/pxvYtpke0T7WS7omJyylhEPWagwMoIkUwqmdu1K9TEVj+6NHGOazi/uG9Tet8wvp32I9KCMl9ZqNhJka1lFTH/kSE80x1uQBDzWMrvU6E04miPlgn/2RQ6FbD18X55NBlvwVv/c2Bcvh2s2xUfQjuL5QSD+oIaosGFpHxO7TXsSHebFWpNd+sSbqllDmw81VHnbWJoEgUmSWiahAu/MsxV0s+WfP/9x78jwsxT/3neb6b5ld8lcopTCKX36dMGApzbhLZEpWx4nDkymW2JSQcgNbfQOHYtBJ960uYql/r/PrT6XrppLsA4h1JtgQTnRVuPNx1Xcj5+7Y5md/5UzLg8dh0qjHaG7uLb8foPZhjNLKAVqCbcm4SX9W93p/FwiqQQjVBLU0osyW+Umnt9tCC7s2wI5SgdApIpoi4It4DEyt+QcEl9wBgUumgKrDAzi/IzAmqkIbmLq7SCi2uxhC9aqJQItnwhg4MvSDjWlu+Yrk8NqDI=
