travis:
  secure:
    BINSTAR_TOKEN: iTX+Zn9oJxQjkfYTMY7CS+iZnwf6PodGMosTFGdbXGk3Umy83zMz5axCOtXpEIgukuGoRGrwq1irhQbhoZ1KTKWktT3hfucXk0KLG4N59j0ya0rDnqKDaRZBHIvtqT9aNNQz77a2GM6pfPwI6XEi8pnuhwXxQjMJ2pnKCx7SBdNr7hqI915/Yc4NkRkUY2IBJgEDmw9nGWkhnsCwGOWmMv9t9eG2XsH3Sbxj/k1vvJFecQctZQAl+aRUZccVY6CKkJx+PljHzCRpjZ5f2yb7wsJLB2N9j3lcuw6UA0VoY1Vyfh67VhDj2n+SAD0nozy7G9s6wsRnU0m3qOcSZooQb9HQow2DyIIttFgT1DTyEwdXQn/A5vBg+p0uVwrYV0NxR+phb6WEFCu+477Gam+t9l/GnVBy5a997VfwjUxuZHp7m2d6MV2LPMCLiIUy1C4njdJXmhmqTfu6Blv2nu5eMGcFGImr5Qj2PV2Z2b3vpuBiaxMCwusQeXvxtQSys9HqzM38cLKQ4+xMwqMtZXsYYoQamAdmMYO7mi9oNx3eZ+xnBNv0CQ1TKIeu3zL86Km41SKEKIumQsmvxD9f08gwOAqVeb1UF7ErnokG6mmX04UaygEj9oORl0aoKrfEcBmzJf2vtYtEHwmB26vm3LmYgvrBEjv0sIecWUO7jZbj4RU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
